### ISSUE TITLE
Upload without given headers produces UnsupportedOperationException

### ISSUE THREAD

**Issue by vvursT** [jlefebure/spring-boot-starter-minio#1]
Collections.EMPTY_MAP is immutable but used as Default-Parameter and will produce an UnsupportedOperationException, because internal putMethod will use it to add the Content-Type-Header later on.

```
if (contentType == null) {
            if (((Map)headerMap).get("Content-Type") == null) {
                ((Map)headerMap).put("Content-Type", "application/octet-stream");
            }
        } else {
            ((Map)headerMap).put("Content-Type", contentType);
        }
```

Replace it with null, thus the internal putObject will initialize it with a mutable HashMap.

**Comment by vvursT** [comment]
Apply #2 for fix.

**Comment by jlefebure** [comment]
Seems good to me, thanks for the fix. I will merge it and deploy a new release including it

**Comment by jlefebure** [comment]
Deploy has been made on release 1.4. Should be available on maven central in 20 minutes
