### ISSUE TITLE
Incompatible with Spring Boot 2.4.0

### ISSUE THREAD

**Issue by Robbilie** [jlefebure/spring-boot-starter-minio#11]
The library is currently incompatible with Spring Boot 2.4.0 due to the usage of:

import org.springframework.boot.actuate.autoconfigure.health.HealthIndicatorAutoConfiguration;

It has been replaced with:

import org.springframework.boot.actuate.autoconfigure.health.HealthContributorAutoConfiguration;

**Comment by SandroHc** [comment]
The PR #12 fixes this. You can use the following dependency in the meantime.

If using Gradle (`build.gradle`):
```groovy
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}
dependencies {
    implementation 'net.sandrohc:spring-boot-starter-minio:1.7-SNAPSHOT'
}
```

If using Maven (`pom.xml`):
```xml
<repositories>
    <repository>
        <id>jitpack.io</id>
        <url>https://jitpack.io</url>
    </repository>
</repositories>
<dependency>
    <groupId>net.sandrohc</groupId>
    <artifactId>spring-boot-starter-minio</artifactId>
    <version>1.7-SNAPSHOT</version>
</dependency>
```

For more information on how this dependency was built, see: https://jitpack.io/#net.sandrohc/spring-boot-starter-minio
